### PR TITLE
Add footer and change favicon and title

### PR DESCRIPTION
**Pull request by CyrusJavan**
Added the footer per this [issue](https://trello.com/c/lmCIRHub/20-website-add-a-sitemap-footer).

Also changed the favicon to the ScalaBridge logo and changed the title to ScalaBridge.

Let me know what y'all think, any recommendations for changes or improvements are appreciated.

### CODE REVIEW

**Comment by xingyif** [comment]
Looks great to me!

Screen Shot 2019-11-14 at 18 11 16
Screen Shot 2019-11-14 at 18 11 23

**Comment by xingyif** [comment]
Also check on mobile. Looks good. +1

Screen Shot 2019-11-14 at 18 14 24

**Comment by zachzwy** [comment]
Looks great! I like the design a lot.

Just a small nitpicks that between 576px and 767px, three social icons are stacked in a column. And the background color doesn't cover the whole footer.

Screen Shot 2019-11-14 at 11 36 30 PM

I personally think it takes more space than needed. I actually don't mind setting 767px as the breakpoint since the user can always navigate to other pages with the sticky navigator.

**Comment by CyrusJavan** [comment]
Good catch @zachzwy! I adjusted so that the sitemap in the footer with not show below 767px. This gets rid of the social icons stacking at those resolutions.

**Pull request merged**
