### PR TITLE
Initial Wireframe for Site Redesign

### PR DESCRIPTION
**Pull request by mattfowler**
Trello Issue: https://trello.com/c/ir8XV0VK/30-website-aboutus-create-a-skeleton-of-the-about-us-page

Includes:
- Mobile friendly collapsable navbar powered by Bootstrap.
- Components for image and text below and to the side (image card and large image card).
- Code of conduct.
- Components for sponsors with placeholder fontawesome icons for now.

Excludes:
- Footer and carousel of event images.  IMO we should do this separately and use something such as glide.js

The CSS could use a little tweaking so I may push to this branch over the next few days but wanted to get early feedback.

Gifs of mobile and desktop experience are below, let me know if there are any issues!

desktop

mobile

### CODE REVIEW

**Comment by xingyif** [comment]
Yay this is amazing! Thank you @mattfowler for the start!

Can you link the Trello issue you worked on?

**Comment by xingyif** [comment]
> Footer and carousel of event images. IMO we should do this separately and use something such as glide.js
Agree with this. Mind to create a Trello card in the TODO column?

> The CSS could use a little tweaking so I may push to this branch over the next few days but wanted to get early feedback.
Agreed. The width of the header can be reduced, size of fonts can also be reduced. We can create cards & separate prs if you'd like.

The website seems require a particular window size to show the header. It would hide the header if the window size is not "big enough". Can we display the header regardless of the window size?
Screen Shot 2019-10-31 at 13 17 14

**Comment by xingyif** [comment]
Ideal header
ezgif com-video-to-gif

**Comment by xingyif** [comment]
current header:
ezgif com-video-to-gif (1)

**Comment by mattfowler** [comment]
> > Footer and carousel of event images. IMO we should do this separately and use something such as glide.js
> > Agree with this. Mind to create a Trello card in the TODO column?
> 
> > The CSS could use a little tweaking so I may push to this branch over the next few days but wanted to get early feedback.
> > Agreed. The width of the header can be reduced, size of fonts can also be reduced. We can create cards & separate prs if you'd like.
> 
> The website seems require a particular window size to show the header. It would hide the header if the window size is not "big enough". Can we display the header regardless of the window size?
> Screen Shot 2019-10-31 at 13 17 14

That's not an issue but I think the question becomes when do we want to start showing the hamburger menu?  Currently the CSS will start to show it at 997px, which is too big I agree.  I can change it so that it only displays when we're on a mobile sized screen if that makes sense.  I will need to trim the left and right padding on the navbar to do this though otherwise the navbar items will get squished together.

**Comment by xingyif** [comment]
> That's not an issue but I think the question becomes when do we want to start showing the hamburger menu?
Having a header gives clear guidance to people who are seeing the website the first time. It will help them to find the information they are looking for/are relevant to them quickly. I am interested in hearing others opinions. @erinzhangxi @zachzwy @KevinEverywhere 

> I can change it so that it only displays when we're on a mobile sized screen if that makes sense. I will need to trim the left and right padding on the navbar to do this though otherwise the navbar items will get squished together.

Sounds good to me. Thank you Matt!

**Comment by zachzwy** [comment]
I think this wireframe is real nice! And you even make it mobile friendly!

I agree the current breakpoint for nav bar is a little big. Here is a good [article](https://ricostacruz.com/til/css-media-query-breakpoints) about breakpoints for reference.

By the way, when will be a good time to merge it with master so that we can pick up what's left based on this code?

**Comment by mattfowler** [comment]
> I think this wireframe is real nice! And you even make it mobile friendly!
> 
> I agree the current breakpoint for nav bar is a little big. Here is a good [article](https://ricostacruz.com/til/css-media-query-breakpoints) about breakpoints for reference.
> 
> By the way, when will be a good time to merge it with master so that we can pick up what's left based on this code?

Thanks!  I can change the breakpoint for the nav bar tomorrow/Sunday and push it.  If we're all OK with it in it's current state after that I'm happy to merge to master then. After that we should be able to parallelize on some of the remaining Trello tasks.

**Comment by spandzgit** [comment]
This is awesome and a great start!

**Comment by zachzwy** [comment]
It looks great to me!

**Comment by xingyif** [comment]
@mattfowler Looks good!

**Review by xingyif — APPROVED** [review]
Great job @mattfowler !

**Pull request merged**
